server:
  port: 8761

spring:
  application:
    name: pegas
#eureka:
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#    enableSelfPreservation: false
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000