server:
  port: 8081

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      routes:
        -id: controller1
        uri: http://localhost:8082
        predicates:
          -Path=/api/v2/**
